### PR TITLE
fix: Changes OIDC to use static URL in Redirect_URI

### PR DESCRIPTION
**Pull request by EthanHeilman**
This PR addresses issue #140 where the randomized redirect URI in the OIDC breaks some OpenID Providers redirect URI allow lists.

Tested with Google with the SSH3 linux running on OSX connecting to SSH3 running on Ubuntu.

### CODE REVIEW

**Comment by francoismichel** [comment]
Would you be okay to keep the previous mechanism in the case where PKCE is not enabled ?

I think one good thing would be to force PKCE at some point but I'm currently unaware of what providers support it.

**Comment by EthanHeilman** [comment]
> Would you be okay to keep the previous mechanism in the case where PKCE is not enabled ?

PKCE was standardized in 2015 and is very widely deployed. The only times I've encountered OPs that don't support PKCE, it is OPs where the attack that PKCE addresses is solved in a different way. For instance the github actions OIDC flow does not use PKCE but the github actions OIDC doesn't use redirect URIs at all:

1. Github Action knows an API key and API secret bound to a specific identity and metadata
2. Github Action makes an API request to github OP which is authenticated with key and secret,
3. Github OP responses to API request with ID Token

I don't see much harm in keeping the redirect URI other than cost of one more configuration option and hitting potential bugs in OPs by having slightly different configuration requirements.

Have you found any cases or OPs where PKCE is both not supported, this randomized redirect URI could be configured and doing so would increase security?

**Comment by francoismichel** [comment]
I found the error, once I merge the bugfix I enable PKCE by default and I can then merge this PR.

**Comment by francoismichel** [comment]
I just reverted your changes to go.mod and go.sum to make the commit clearer.

Thanks for the PR ! It helps a lot!

**Pull request merged**
