### PR TITLE
implement missing features from openssh

### PR DESCRIPTION
**Pull request by pg83**
* retry command after adding host hash into .ssh3/known_hosts
* try all available ssh agent keys
* inherit PATH and other vars from daemon (actually do not know about openssh behavior, implement dropbear's `-e` option)

### CODE REVIEW

**Comment by francoismichel** [comment]
Thanks for the PR ! 

Can you reformat the code with `go vet` ?

**Comment by pg83** [comment]
> Thanks for the PR !
> 
> Can you reformat the code with `go vet` ?

done, iff you mean `go fmt`

**Review by francoismichel — CHANGES_REQUESTED** [review]
Thanks again for the PR !

I added a few comments about running the auth process in a loop, that need to be addressed before being merged.

I am more skeptical about the user environment part: they raise security concernts and I think the best way would be to add support for PAM instead.

As this PR is in two parts ((i) user auth in a loop and (ii) environment variables inhrietance), I'd suggest focusing on (i) now and dropping (ii) until we find a good way forward.

**Comment by pg83** [comment]
Have no spare time to remake this PR properly :(

**Pull request closed without merging**
