### PR TITLE
draft: fix(util): match non-pointer public key types

### LINKED ISSUE #38: `Unknown signing method: ed25519.PublicKey` error?
Hi there, thank you for this amazing piece of software that I have been waiting for so long (but now, I can even contribute to it!).

I am packaging ssh3 inside the NixOS distribution for mostly experimental users (not as a sshd replacement obviously) and I am writing an integration test for it and I see on the client:

```
client # 4:40PM DBG dialing QUIC host at server.ssh.acme.test:443
client # 4:40PM DBG QUIC handshake complete
client # 4:40PM WRN Could not load private key: unknown signing method: ed25519.PublicKey
client # 4:40PM ERR no suitable identity found
```

with an ED25519 key generated by `ssh-keygen` from OpenSSH tooling, does that ring a bell? Reading the source code, I cannot understand why this pattern match case fails, I am not a big Go developer in general so I may be missing something I assume.

Thank you!

### PR DESCRIPTION
**Pull request by TheoTechnicguy**
This PR aims to fix #38. Some `pubkey`s passed to the function are not pointers, but are still valid keys. This commit fixes this bug by adding the non-pointer types to the switch. Furthermore, more debugging log prints are added.

I am submitting this PR as a draft, as integration tests do not pass (see [this comment](https://github.com/francoismichel/ssh3/pull/45#issuecomment-1859118891)).

### CODE REVIEW

**Comment by francoismichel** [comment]
Thank you for the PR!

It should now work in integration tests if you rebase your branch on main.

What would be nice as well is to add an integration test case with ed25519 similar to the `It("Should connect using privkey"` test case. I added an ed25519 in the CI scripts accessible in the integration tests through the `TESTUSER_ED25519_PRIVKEY` environment variable. Would you feel like adding a test case using that key as well ? I can work on that otherwise.

**Comment by TheoTechnicguy** [comment]
I agree that creating a test case for this is a good idea. I'd have to look up how to do that with Ginko, which might take a while. Furthermore, I am working on adding a bit more debug logging (draft PR coming up), which will help to get better bug reports (also, I already know `zerolog`, so this is easier for me :yum:). Not wanting to discredit the value of testing, the latter one seems more important to me, as it will help with bug reports.

Depending on your judgment, I can hand over none, one or both PRs and/or reprioritize these.

**Comment by francoismichel** [comment]
Do it as you like the most, I can add the testcase on this PR myself as well, it would not take me much time so it is as you prefer. :-)

**Comment by TheoTechnicguy** [comment]
In that case, I'll extend the debug logging ^^.

**Comment by francoismichel** [comment]
Merged as [6127e06](https://github.com/francoismichel/ssh3/commit/6127e06c505d0c0011a2a4beed28b46a0edb0b3b), thank you !

**Pull request merged**
